### Part 1: Functions

In [15]:
def double(x):
    return x * 2

In [16]:
# prediction: 10
double(5)

10

In [17]:
# prediction: error
double("CS")

'CSCS'

In [18]:
courses = ["CS106A", "CS106B", "MATH51", "CS109"]

In [19]:
def first_and_last(items):
    return items[0], items[-1]

In [20]:
#prediction: ("CS106A", "CS109")
first_and_last(courses)

('CS106A', 'CS109')

In [21]:
# prediction: 20
result = double(10)
print(result)

20


In [22]:
# prediction: "hello!"
def shout(word):
    print(word + "!")

result = shout("hello")
print(result)

hello!
None


In [23]:
def letter_grade_to_points(grade):
    if grade == "A":
        return 4.0
    elif grade == "A-":
        return 3.7
    elif grade == "B+":
        return 3.3
    else:
        return 0.0

In [24]:
# predictions: 4.0, 3.7, 3.3, 0.0
print(letter_grade_to_points("A"))
print(letter_grade_to_points("A-"))
print(letter_grade_to_points("B+"))
print(letter_grade_to_points("C"))

4.0
3.7
3.3
0.0


In [25]:
letter_grades = ["A", "A-", "B+"]

In [26]:
# prediction: [4.0, 3.7, 3.3]
[letter_grade_to_points(grade) for grade in letter_grades]

[4.0, 3.7, 3.3]

### Part 2: Boolean Masks

In [27]:
import numpy as np
wages = np.array([45000, 82000, 31000, 120000, 67000])

In [28]:
# prediction: [90000, 164000, 62000, 240000, 134000]
wages * 2

array([ 90000, 164000,  62000, 240000, 134000])

In [29]:
# prediction: [45, 82, 31, 120, 67]
wages / 1000

array([ 45.,  82.,  31., 120.,  67.])

In [30]:
[45000, 82000] * 2

[45000, 82000, 45000, 82000]

In [ ]:
# Prediction: [82000, 120000, 67000]
wages > 60000

array([False,  True, False,  True,  True])

In [32]:
# Prediction: [82000, 120000, 67000]
wages[wages > 60000]

array([ 82000, 120000,  67000])

In [33]:
# Prediction: []
wages[wages > 200000]

array([], dtype=int64)

In [34]:
# Prediction: 3
(wages > 60000).sum()

np.int64(3)

In [35]:
# Prediction: 0.6
(wages > 60000).mean()

np.float64(0.6)

### Part 3: None and Missing Values

In [36]:
x = None
print(x)

None


In [37]:
# Prediction: True
None == None

True

In [ ]:
# Prediction: error
# None + 5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [39]:
messy = np.array([45000, None, 31000], dtype=float)
messy

array([45000.,    nan, 31000.])

In [40]:
# Prediction: error
messy.mean()

np.float64(nan)

In [42]:
# Prediction: 38000.0
np.nanmean(messy)

np.float64(38000.0)